### ISSUE TITLE
M65: Injecting a basic prg with m65 not working properly

### ISSUE THREAD

**Issue by hstampfl** [MEGA65/mega65-tools#40] opened 2021-02-13 15:55 UTC
Injecting a BASIC V10 prg with m65 tool does not get correctly injected.
The program get transfered and it correctly starts, but editing the program crashes the mega65.

This issue was not seen before because an assembly program mostly won't be edited after executing.

See more details on discord:
https://discord.com/channels/719326990221574164/795760112425369610/809155791718187060

Use following steps to reproduce:
1. unzip and transfer attached program with m65 (on windows: m65 -l COMxxx -F -r rasterwait.prg)
2. Press RUN/STOP
3. Execute LIST
4. Edit last Line and press RETURN
5. You should see an similar screen as attached screenshot.
6. 
![mega65-screen-basic_injection_issue](https://user-images.githubusercontent.com/11168045/107854449-2db66580-6e1c-11eb-8ff9-127a24e076db.png)

[rasterwait.zip](https://github.com/MEGA65/mega65-tools/files/5975957/rasterwait.zip)

**Comment by Edilbert** [comment] 2021-02-15 11:06
After transferring the program, the pointer "text_top" ($82/$83) must be set to the end of the program text.
It is the same value, like the (eal/eah) = End Address Load = ($ae/$af).
The editor needs this information, if not set to the correct value, the editor will produce strange results or crash.

**Comment by gardners** [comment] 2021-04-25 11:20
In _theory_ this should be correctly handled by having the X and Y registers loaded with the top address of the LOAD.
But now that we trap the LOAD vector in a more generic manner (see commit for fixing issue #2 ), we probably need to set this directly.

**Comment by gardners** [comment] 2021-04-25 11:25
Seems to be fixed by the above.

**Comment by gurcei** [comment] 2021-04-25 14:20
I've confirmed that this has resolved the issue.

**Closed by gurcei** 2021-04-25 14:20 UTC
